name: run

on: 
    workflow_dispatch:

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
        
        - name: checkout repo content
          uses: actions/checkout@v3
          with:
            repository: IdeaProjects/Smart-API-Automation
          
        - name: setup python
          uses: actions/setup-python@v4
          with: 
            python-version: '3.9'
          
        - name: execute py script
          run: python Smart-API-Automation/IdeaProjects/SmartAPIautomationframework/src/test/java/examples/users/pythonController/DataValidators.py
