name: Smart API Automation Framework

on: 
    workflow_dispatch:

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
        
        - name: checkout repo content
          uses: actions/checkout@v3
          with:
            repository: tushar-lakhe/Smart-API-Automation
          
        - name: setup python
          uses: actions/setup-python@v4
          with: 
            python-version: '3.9'
          
        - name: Install Py libs
          run: |
                pip3 install datetime
                pip3 install openpyxl
                pip3 install ujson
                pip3 install pathlib
        
        - name: List Dir
          run: |
                pwd
                which bash
                ls
                cd IdeaProjects/SmartAPIautomationframework/src/test/java/examples/users/pythonController
                ls
        
                 
        - name: Smart Api Automation execute
          run: |
                cd IdeaProjects
                ls
                chmod +x Run.sh
                bash Run.sh
    
        - name: Upload artifact 
          uses: actions/upload-artifact@master
          with:
            name: my-artifact
            path: |
                    target/gatling/*.*
                    target/cucumber-html-reports/*.*

