name: run

on: 
    workflow_dispatch:

jobs:
 build:
    runs-on: windows-latest
    steps:
        
        - name: checkout repo content
          uses: action/checkout@v2
          
        - name: setup python
          uses: action/setup-python@v4
          with: 
            python-version: '3.9'
          
        - name: execute py script
          run: python Smart-API-Automation/IdeaProjects/SmartAPIautomationframework/src/test/java/examples/users/pythonController/DataValidators.py
