name: Smart API Automation FW test
# Controls when the workflow will run
on:
    workflow_dispatch:
        
jobs:

    test:
        runs-on: ubuntu-latest
        steps:

            - name: setup python
              uses: actions/setup-python@v4
              with: 
                python-version: '3.9'

            - name: Install required libs
              run: |
                    pip3 install datetime
                    pip3 install openpyxl
                    pip3 install ujson
                    pip3 install pathlib

            - name: Setup Maven 
              uses: s4u/setup-maven-action@v1.2.1
              with:
                    java-version: 8             

           
            - name: checkout Regression Test Suit
              uses: actions/checkout@v3
              with:
                repository: tushar-lakhe/Smart-API-Automation
                token: ${{ secrets.GITHUB_TOKEN }}
                path: IdeaProjects



            
