name: run

on: 
    workflow_dispatch:

jobs:
 build:
    runs-on: windows-latest
    steps:
        
        - name: checkout repo content
          uses: actions/checkout@v3
          with:
            repository: tushar-lakhe/Smart-API-Automation
          
        - name: setup python
          uses: actions/setup-python@v4
          with: 
            python-version: '3.9'
        
        - name: List dir
          run: |
                pwd
                ls
                cd D:\a\Smart-API-Automation\Smart-API-Automation
                ls
                
          
        - name: execute py script
          run: |
                cd D:/a/Smart-API-Automation/Smart-API-Automation/src/test/java/examples/users/pythonController/
                python DataValidators.py
