name: Smart API Automation FW test
# Controls when the workflow will run
on:
    workflow_dispatch:
        
jobs:

    test:
        runs-on: ubuntu-latest
        steps:

            - name: setup python
              uses: actions/setup-python@v4
              with: 
                python-version: '3.9'

            - name: Install required libs
              run: |
                    pip3 install datetime
                    pip3 install openpyxl
                    pip3 install ujson
                    pip3 install pathlib

            - name: Setup Maven 
              uses: s4u/setup-maven-action@v1.2.1
              with:
                    java-version: 8             

           
            - name: checkout Regression Test Suit
              uses: actions/checkout@v3
              with:
                repository: tushar-lakhe/Smart-API-Automation
                token: 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
                path: IdeaProjects



            - name: Smart Api Automation execution for Api Test/Regression
              run: |
                    echo "####################################################################################################"
                    echo "######################################  Initialising Test ##########################################"
                    echo "####################################################################################################"
                    echo "####################################################################################################"
                    echo "####################################  Validating user inputs #######################################"
                    echo "####################################################################################################"
                    cd IdeaProjects/IdeaProjects/SmartAPIautomationframework//src//test//java//examples//users//pythonController//
                    python DataValidator.py
                    echo "####################################################################################################"
                    echo "############################### User inputs validation Completed ###################################"
                    echo "####################################################################################################"
                    echo "####################################################################################################"
                    echo "################################## Generating Feature Files... #####################################"
                    echo "####################################################################################################"
                    python3 FeatureGenerator.py

                    echo "####################################################################################################"
                    echo "################################## Feature Files Generated Successfully ##################################"
                    echo "##############################################################"
                    echo "####################################################################################################"
                    echo "#################################### Test Execution Begins... ##############################################"
                    echo "############################################################################################################"
                    python3 ReportGeneratorAPI.py

            - name: Generate and Upload Karate Report 
              uses: actions/upload-artifact@v3
              with:
                name: Karate Report
                path: |
                       IdeaProjects/IdeaProjects/SmartAPIautomationframework/target/cucumber-html-reports/*

            - name: Smart Api Automation execution for Perf Test
              run: | 
                   cd IdeaProjects/IdeaProjects/SmartAPIautomationframework//src//test//java//examples//users//pythonController//
                   python3 ReportGeneratorPerf.py


            - name: Generate and Upload Gatling Report 
              uses: actions/upload-artifact@v3
              with:
                name: Gatling Report
                path: |
                       IdeaProjects/IdeaProjects/SmartAPIautomationframework/target/gatling/*
