name: run

on: 
    schedule:
        - cron: '5 * * * *'

jobs:
 build:
    runs-on: windows-latest
    steps:
        
        - name: checkout repo content
          uses: action/checkout@v2
          
        - name: setup python
          uses: action/setup-python@v4
          with: 
            python-version: '3.9'
          
        - name: execute py script
          run: python DataValidators.py
